/**
 * `harnesskit ingest` command.
 *
 * Scans docs/references/ for user-dropped source documents (PRDs, architecture
 * docs, requirement specs, API docs, etc.), then generates a structured
 * "ingest instruction" that the user's coding agent can execute to auto-populate
 * all Source-of-Truth files (ARCHITECTURE.md, SECURITY.md, QUALITY_SCORE.md, etc.).
 *
 * Why this design?
 *   - Zero dependencies: the SDK can't call LLMs directly
 *   - IDE-agnostic: works with any coding agent (Copilot, Cursor, Claude, etc.)
 *   - The coding agent IS the LLM — we just give it the right instruction
 */

import { existsSync, readdirSync, readFileSync, statSync, mkdirSync, writeFileSync } from 'node:fs';
import { join, relative, extname } from 'node:path';
import { heading, step, fail, info, warn, color, bold } from '../ui.js';

const SUPPORTED_EXTENSIONS = ['.md', '.txt', '.rst', '.adoc', '.yaml', '.yml', '.json', '.csv', '.xml', '.html'];

const SOT_FILES = [
  { file: 'docs/ARCHITECTURE.md', what: 'Architecture layers, dependency rules, key directories, domain boundaries' },
  { file: 'docs/SECURITY.md', what: 'Auth mechanisms, secrets management, data classification, dependency policy' },
  { file: 'docs/RELIABILITY.md', what: 'Health endpoints, SLA targets, failure modes, deployment safety, CI/CD' },
  { file: 'docs/QUALITY_SCORE.md', what: 'Per-domain quality grades (A-F), coverage gaps, known issues' },
  { file: 'docs/design-docs/', what: 'Key decisions, trade-offs, options considered — one file per decision' },
  { file: 'docs/exec-plans/active/', what: 'Execution plans for upcoming work — one file per task' },
  { file: 'docs/product-specs/', what: 'User stories, acceptance criteria, feature requirements' },
  { file: 'AGENTS.md', what: 'Project description, build commands, quick-map table — keep under 100 lines' },
];

export async function ingest(targetDir) {
  heading('Harness Lab Ingest');

  const refsDir = join(targetDir, 'docs', 'references');

  // ─── Check if references/ exists and has files ──────────────────
  if (!existsSync(refsDir)) {
    mkdirSync(refsDir, { recursive: true });
    info(`Created docs/references/ — drop your source docs there first.`);
    console.log(`
${bold('How to use ingest:')}

  1. ${color('Drop your existing docs', 'yellow')} into ${color('docs/references/', 'cyan')}:
     - PRDs, architecture docs, requirement specs
     - API documentation, design decisions
     - Anything that describes what you're building

  2. Run ${color('harnesskit ingest', 'cyan')} again

  3. The command generates an ${color('ingest instruction', 'green')} file

  4. ${color('Paste that instruction', 'yellow')} into your coding agent (Copilot, Cursor, Claude)

  5. The agent reads your reference docs and ${color('auto-populates all SoT files', 'green')}
`);
    return;
  }

  // ─── Scan for source documents ──────────────────────────────────
  const sourceFiles = scanForDocs(refsDir);

  if (sourceFiles.length === 0) {
    warn('No documents found in docs/references/');
    console.log(`
  Drop your source docs (PRD, architecture, requirements, API docs) into:
    ${color('docs/references/', 'cyan')}

  Supported formats: ${SUPPORTED_EXTENSIONS.join(', ')}
`);
    return;
  }

  info(`Found ${sourceFiles.length} source document(s) in docs/references/\n`);
  for (const f of sourceFiles) {
    step(f.relativePath);
  }

  // ─── Build the ingest instruction ───────────────────────────────
  heading('Generating ingest instruction...');

  const fileList = sourceFiles.map((f) => `- \`${f.relativePath}\` (${f.sizeKB} KB)`).join('\n');

  const fileSummaries = sourceFiles.map((f) => {
    const preview = f.content.slice(0, 500).replace(/\n/g, '\n    ');
    return `### ${f.relativePath}\n\`\`\`\n    ${preview}${f.content.length > 500 ? '\n    ...(truncated)' : ''}\n\`\`\``;
  }).join('\n\n');

  const sotTargets = SOT_FILES.map((s) => `- **${s.file}** — Extract: ${s.what}`).join('\n');

  const instruction = `# Ingest Instruction — Auto-Populate Source-of-Truth Files

> **Generated by \`harnesskit ingest\` on ${new Date().toISOString().split('T')[0]}**
> Copy-paste this ENTIRE file into your coding agent (Copilot Chat, Cursor, Claude Code, etc.)

---

## Your Task

Read ALL the reference documents listed below. Extract the relevant information and **populate the Source-of-Truth (SoT) files** in this repository. Do NOT copy-paste — synthesize and structure the information according to each SoT file's format.

## Source Documents Found

${fileList}

## Target SoT Files to Populate

${sotTargets}

## Instructions Per Target

### 1. docs/ARCHITECTURE.md
Read the reference docs and update:
- **Layer diagram**: Identify the application's architectural layers (e.g., Types → Config → Service → Routes)
- **Dependency rules table**: Which layers can import from which
- **Key directories**: Map source folders to their architectural role
- **Domain boundaries**: What business domains exist

### 2. docs/SECURITY.md
Extract and fill in:
- **Authentication mechanisms**: How users/services authenticate
- **Secrets management**: Where secrets are stored, rotation policy
- **Data classification table**: What data is Public/Internal/Confidential/Restricted
- **Dependency policy**: Any security-related dependency rules

### 3. docs/RELIABILITY.md
Extract and fill in:
- **Boot commands**: How to start the application from scratch
- **Health endpoints**: Any health check or readiness probe URLs
- **SLA targets**: Uptime, latency, error rate targets
- **Failure modes**: Known failure scenarios and mitigations

### 4. docs/QUALITY_SCORE.md
For each domain/module mentioned in the reference docs:
- Assign an initial quality grade (A-F) based on maturity
- Note any known gaps or missing test coverage

### 5. docs/design-docs/
For each significant architectural decision in the reference docs:
- Create a design doc: \`docs/design-docs/YYYY-MM-DD-short-title.md\`
- Use the template in \`docs/design-docs/README.md\`

### 6. docs/exec-plans/active/
For any planned work, upcoming features, or TODOs mentioned:
- Create an execution plan: \`docs/exec-plans/active/task-name.md\`
- Use the template in \`docs/exec-plans/active/_template.md\`

### 7. docs/product-specs/
For any user stories, acceptance criteria, or feature requirements:
- Create product spec files in \`docs/product-specs/\`

### 8. AGENTS.md
Update the project description and any build/run commands that differ from the current values.

## Reference Document Previews

${fileSummaries}

## Rules
- **Do NOT delete** existing content in SoT files — merge with what's already there
- **Do NOT copy-paste** raw text — synthesize and structure it
- Replace \`<!-- ... -->\` placeholder comments with real values
- Keep AGENTS.md under 100 lines
- After populating, run \`harnesskit doctor\` to verify completeness
- After populating, run \`harnesskit enforce\` to check architecture compliance
`;

  // ─── Write the instruction file ─────────────────────────────────
  const instructionPath = join(targetDir, 'docs', 'generated', 'INGEST_INSTRUCTION.md');
  mkdirSync(join(targetDir, 'docs', 'generated'), { recursive: true });
  writeFileSync(instructionPath, instruction, 'utf-8');
  step('docs/generated/INGEST_INSTRUCTION.md');

  // ─── Summary ───────────────────────────────────────────────────
  heading('Ready!');
  console.log(`
${bold('Ingest instruction generated.')}

${color('What to do next:', 'cyan')}

  ${color('Option A — IDE Agent (recommended):', 'green')}
    1. Open your IDE (VS Code, Cursor, Claude Code, etc.)
    2. Open ${color('docs/generated/INGEST_INSTRUCTION.md', 'yellow')}
    3. Select all text and paste into the agent chat
    4. The agent will read your reference docs and populate all SoT files

  ${color('Option B — Copilot CLI:', 'green')}
    $ gh copilot explain "Follow the instructions in docs/generated/INGEST_INSTRUCTION.md"

  ${color('Option C — Claude Code:', 'green')}
    $ claude "Follow the instructions in docs/generated/INGEST_INSTRUCTION.md"

${color('After ingestion, verify:', 'yellow')}
    $ npx harnesskit doctor     # Check all SoT files are populated
    $ npx harnesskit enforce    # Validate architecture rules
`);
}

function scanForDocs(dir) {
  const results = [];
  try {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = join(dir, entry.name);
      if (entry.isDirectory()) {
        results.push(...scanForDocs(full));
      } else if (SUPPORTED_EXTENSIONS.includes(extname(entry.name).toLowerCase())) {
        try {
          const content = readFileSync(full, 'utf-8');
          const stat = statSync(full);
          results.push({
            fullPath: full,
            relativePath: 'docs/references/' + relative(dir, full).replace(/\\/g, '/'),
            sizeKB: Math.ceil(stat.size / 1024),
            content,
          });
        } catch { /* skip unreadable files */ }
      }
    }
  } catch { /* skip directories we can't read */ }
  return results;
}
